### ISSUE TITLE
Investigate implementing "Cache-Control" headers.

### ISSUE THREAD

**Issue by benslv** [benslv/insync#6]
A method for reducing the load of our application on Spotify's API would be to find a way to get the browser to cache some information about the user so it doesn't have to fetch it over and over again, which could potentially cause rate-limit errors.

The data we could cache would be:
- a list of the artist URIs that the user follows
- a JSON structure of the top tracks for each of the artists that the user follows

Obviously this introduces the concern over stale data and whether users will be annoyed that some of the information (e.g. the artists they follow) isn't kept up to date in real time. I'd say we don't need to cache it for very long...even 5-10 minutes would massively help if people are generating lots of playlists very quickly.

I imagine this would involve rewriting some of the `generate.server.ts` code to utilise Remix loaders so they can return a `Response` with cache headers added, as I don't think it's possible any other way.

---

I think the coolest way of caching the data IN GENERAL would be to actually store the information about individual artists' top tracks as some kind of key-value store, so we can ping the cache and look for the information before requesting it from the server. The benefit of this is it would keep people's follow lists up-to-date in realtime and also could be reused across different users. Might be possible to do something with Vercel's Edge Stores... Just need to find a way to keep each entry under 8KB

**Comment by benslv** [comment]
Now that I've written it all up I think a bit of Edge computing could be our solution here, and finding a way to store each artist's top tracks in a key-value store that *every* client can access. Fetching the data about "followed artists" is cheap because you can batch them; it's the huge number of concurrent requests going out to Spotify about top tracks that brings in the 429s.

**Comment by eeme1i** [comment]
I'm not very knowledgeable when it comes caching and this sort of stuff, so there's not a lot I can say. The edge computing method sounds sick though lol
